#FROM registry.redhat.io/rhel9-4-els/rhel:9.4 AS builder
#FROM registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:v1.23.4-202502100816.g6c23478.el9 AS builder
#FROM golang:1.23 as builder

FROM quay.io/centos/centos:10

RUN ["dnf", "install", "-y", "golang"]
RUN ["mkdir", "/opt/kmm"]
WORKDIR /opt/kmm

COPY kernel-module-management .
RUN go build -ldflags="-w -s -X main.Version=${CI_VERSION} -X main.GitCommit=${CI_UPSTREAM_SHORT_COMMIT}" -o worker ./cmd/worker

