---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/releasePlanAdmission: kmm-24
    release.appstudio.openshift.io/standing-attribution: "true"
  name: kmm-24-releaseplan
  namespace: rh-kmm-tenant
spec:
  application: kmm-24
  target: rhtap-releng-tenant

