---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/releasePlanAdmission: rh-kmm-2.4-rhel-9
    release.appstudio.openshift.io/standing-attribution: "true"
  name: rh-kmm-2.4-rhel-9-releaseplan
  namespace: rh-kmm-tenant
spec:
  application: kernel-module-management
  target: rhtap-releng-tenant

