#!/bin/bash

BRANCH=""

if [ "$1" == "--auto" ]; then
    AUTO="true"
    shift

    git config --global user.name "autoupdate"
    git config --global user.email "github-actions[bot]@users.noreply.github.com"
fi

if [ "$1" == "--branch" ]; then
    BRANCH=$2
    echo "pushing to $BRANCH"
    shift
    shift
fi

#REPODIR=$(git rev-parse --show-toplevel)
#. ${REPODIR}/scripts/functions.sh

if  [ -z  "$AUTO" ]; then
    git submodule update --remote
    COMMIT=$(git submodule status | awk -v module=$MODULE '$2==module{gsub("+","");print substr($1,0,7)}')
fi


echo "OP before: $(md5sum kernel-module-management.clusterserviceversion.yaml)"
echo "hub before: $(md5sum kernel-module-management-hub.clusterserviceversion.yaml)"

scripts/make-csv.py --csv kernel-module-management/bundle/manifests/kernel-module-management.clusterserviceversion.yaml --out kernel-module-management.clusterserviceversion.yaml
scripts/make-csv.py --csv kernel-module-management/bundle-hub/manifests/kernel-module-management-hub.clusterserviceversion.yaml --out kernel-module-management-hub.clusterserviceversion.yaml

echo "OP after: $(md5sum kernel-module-management.clusterserviceversion.yaml)"
echo "hub after: $(md5sum kernel-module-management-hub.clusterserviceversion.yaml)"

git add kernel-module-management kernel-module-management.clusterserviceversion.yaml kernel-module-management-hub.clusterserviceversion.yaml

if [ $? -ne 0 ]; then
    echo "git add failed, nothing to add?"
    exit 0
fi

git commit -m "update autogenerated files $COMMIT"

if [ -n  "$AUTO" ]; then
    git push origin $BRANCH
fi
