apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/chr15p/rh-kmm-konflux?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "release-2.4" &&
      (".tekton/operator-bundle-24-pull-request.yaml".pathChanged() || 
      ".tekton/operator-bundle-24-push.yaml".pathChanged() || 
      "bundle-hack/operator.pullspec".pathChanged() ||
      "Dockerfile.operator-bundle".pathChanged() ||
      "kernel-module-management".pathChanged())
  creationTimestamp: null
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: kernel-module-management
    appstudio.openshift.io/component: operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: operator-bundle-on-push
  namespace: rh-kmm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-kmm-tenant/operator-bundle:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
  - name: dockerfile
    value: Dockerfile.operator-bundle
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
