apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/chr15p/rh-kmm-konflux?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-2.4" &&
      (".tekton/webhook-24-pull-request.yaml".pathChanged() ||
      ".tekton/webhook-24-push.yaml".pathChanged() ||
      "bundle-hack/signing.pullspec".pathChanged() ||
      "Dockerfile.webhook".pathChanged() ||
      "kernel-module-management".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: kmm-24
    appstudio.openshift.io/component: webhook-24
    pipelines.appstudio.openshift.io/type: build
  name: webhook-24-on-push
  namespace: rh-kmm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-kmm-tenant/kmm-24/webhook-24:{{revision}}
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  - name: dockerfile
    value: Dockerfile.webhook
  - name: path-context
    value: .
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
