---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: fbc-op-v2-4-416-r49-5-prod
  namespace: rh-kmm-tenant
  labels:
    appstudio.openshift.io/application: fbc-op-v2-4-416
spec:
  releasePlan: fbc-op-v2-4-416-release-prod
  snapshot: fbc-op-v2-4-416-72nhb

